apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-arch-wiki
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-arch-wiki
  template:
    metadata:
      labels:
        app: iot-arch-wiki
    spec:
      containers:
        - name: iot-arch-wiki
          image: iot-arch-wiki:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: iot-arch-wiki-balancer
spec:
  selector:
    app: iot-arch-wiki
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
